# Generated by Django 2.2.12 on 2020-12-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kategori',
        ),
    ]
