# Generated by Django 2.2.12 on 2020-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201225_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
