# Generated by Django 2.2.12 on 2020-12-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='nomor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
